import assert from 'node:assert/strict';
import test from 'node:test';
import { OandaReadError, oandaReadRequest, type OandaReadDiagnostic } from '../utils/oanda/api/request.ts';
import { candleCollectorJitterMs, runSequentially, workerScanJitterMs } from '../utils/workerRuntime.ts';

const secret='token-never-log',account='account-never-log';
const credential=(token=secret)=>({environment:'demo' as const,accountId:account,token,baseUrl:'https://api-fxpractice.oanda.com',streamUrl:'x'});
const run=(responses:Response[],overrides:Record<string,unknown>={})=>{
  const diagnostics:OandaReadDiagnostic[]=[],urls:string[]=[],headers:string[]=[],sleeps:number[]=[];
  let reads=0,calls=0;
  const promise=oandaReadRequest({operation:'test_read',endpointTemplate:'/v3/accounts/{account}/openTrades',mode:'demo',pair:'EUR/USD',
    buildPath:({accountId})=>`/v3/accounts/${accountId}/openTrades`,retryJitterMinMs:10,retryJitterMaxMs:20,
    dependencies:{fetch:async(input,init)=>{calls++;urls.push(String(input));headers.push(String(new Headers(init?.headers).get('Authorization')));return responses.shift()!},
      credentials:()=>{reads++;return credential(`secret-${reads}`)},random:()=>0.5,
      sleep:async milliseconds=>{sleeps.push(milliseconds)},diagnostic:value=>diagnostics.push(value),...(overrides as any)} });
  return {promise,diagnostics,urls,headers,sleeps,get reads(){return reads},get calls(){return calls}};
};

test('GET succeeds on the first attempt',async()=>{const state=run([new Response('{}',{status:200})]);assert.equal((await state.promise).status,200);assert.equal(state.calls,1)});
test('one 401 is retried and succeeds',async()=>{const state=run([new Response('',{status:401}),new Response('{}',{status:200})]);await state.promise;assert.equal(state.calls,2);assert.equal(state.diagnostics.at(-1)?.retrySucceeded,true)});
test('retry success is consumed once, so candle processing cannot duplicate',async()=>{let jsonCalls=0;const final=new Response('{}',{status:200});Object.defineProperty(final,'json',{value:async()=>{jsonCalls++;return {candles:[{time:'2026-01-01T00:00:00Z'}]}}});const state=run([new Response('',{status:401}),final]);const response=await state.promise;const parsed=await response.json();assert.equal(parsed.candles.length,1);assert.equal(jsonCalls,1)});
test('two 401 responses fail closed and exhaust retry',async()=>{const state=run([new Response('',{status:401}),new Response('',{status:401})]);await assert.rejects(state.promise,OandaReadError);assert.equal(state.diagnostics.at(-1)?.retryExhausted,true)});
test('credentials are re-read and retry occurs exactly once',async()=>{const state=run([new Response('',{status:401}),new Response('',{status:401}),new Response('{}')]);await assert.rejects(state.promise);assert.equal(state.reads,2);assert.equal(state.calls,2);assert.notEqual(state.headers[0],state.headers[1])});
test('retry jitter is bounded',async()=>{const state=run([new Response('',{status:401}),new Response('{}')]);await state.promise;assert.deepEqual(state.sleeps,[15])});
test('one timeout is retried and succeeds',async()=>{const diagnostics:OandaReadDiagnostic[]=[];let calls=0;const response=await oandaReadRequest({operation:'timeout',endpointTemplate:'/x',mode:'demo',timeoutMs:5,retryJitterMinMs:0,retryJitterMaxMs:0,buildPath:()=>'/x',dependencies:{fetch:async(_input,init)=>{calls++;if(calls===2)return new Response('{}');return new Promise((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(init.signal?.reason),{once:true}))},credentials:()=>credential(),sleep:async()=>{},diagnostic:value=>diagnostics.push(value)}});assert.equal(response.status,200);assert.equal(calls,2);assert.equal(diagnostics[0].timeout,true);assert.equal(diagnostics[0].retryScheduled,true);assert.equal(diagnostics[1].retrySucceeded,true)});
test('two timeouts fail closed and exhaust retry',async()=>{const diagnostics:OandaReadDiagnostic[]=[];let calls=0;await assert.rejects(oandaReadRequest({operation:'timeout',endpointTemplate:'/x',mode:'demo',timeoutMs:5,retryJitterMinMs:0,retryJitterMaxMs:0,buildPath:()=>'/x',dependencies:{fetch:async(_input,init)=>{calls++;return new Promise((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(init.signal?.reason),{once:true}))},credentials:()=>credential(),sleep:async()=>{},diagnostic:value=>diagnostics.push(value)}}),OandaReadError);assert.equal(calls,2);assert.equal(diagnostics.at(-1)?.retryExhausted,true)});
test('shutdown aborts pending retry jitter',async()=>{const controller=new AbortController();let secondFetch=false;const promise=oandaReadRequest({operation:'abort',endpointTemplate:'/x',mode:'demo',signal:controller.signal,buildPath:()=>'/x',dependencies:{fetch:async()=>{if(secondFetch)throw new Error('unexpected retry');secondFetch=true;return new Response('',{status:401})},credentials:()=>credential(),sleep:async(_ms,signal)=>new Promise<void>((_r,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true})),diagnostic:()=>{}}});setTimeout(()=>controller.abort(),5);await assert.rejects(promise);});
test('workers do not share mutable credentials',async()=>{let value=0;const credentials=()=>credential(`token-${++value}`);const seen:string[]=[];await Promise.all([1,2].map(()=>oandaReadRequest({operation:'parallel',endpointTemplate:'/x',mode:'demo',buildPath:()=>'/x',dependencies:{credentials,fetch:async(_u,i)=>{seen.push(String(new Headers(i?.headers).get('Authorization')));return new Response('{}')},diagnostic:()=>{}}})));assert.equal(new Set(seen).size,2)});
test('diagnostics and errors contain no token, account ID, URL, or authorization header',async()=>{const state=run([new Response('',{status:403})]);let error='';try{await state.promise}catch(value){error=String(value)+JSON.stringify(value)}const serialized=error+JSON.stringify(state.diagnostics);for(const sensitive of [secret,account,'secret-1','Authorization','api-fxpractice'])assert.doesNotMatch(serialized,new RegExp(sensitive,'i'))});
test('invalid credentials fail locally without network access',async()=>{let called=false;await assert.rejects(oandaReadRequest({operation:'invalid',endpointTemplate:'/x',mode:'live',buildPath:()=>'/x',dependencies:{credentials:()=>{throw new Error('OANDA_LIVE_ACCOUNT_TOKEN is required')},fetch:async()=>{called=true;return new Response()},diagnostic:()=>{}}}),/OANDA_LIVE_ACCOUNT_TOKEN/);assert.equal(called,false)});
test('request ID is captured and missing IDs are safe',async()=>{const withId=run([new Response('{}',{headers:{RequestID:'req-1'}})]);await withId.promise;assert.equal(withId.diagnostics[0].requestId,'req-1');const without=run([new Response('{}')]);await without.promise;assert.equal(without.diagnostics[0].requestId,undefined)});
test('openNow-style diagnostics preserve the real HTTP status',async()=>{const diagnostics:OandaReadDiagnostic[]=[];await assert.rejects(oandaReadRequest({operation:'open_trades',endpointTemplate:'/v3/accounts/{account}/openTrades',mode:'demo',buildPath:()=>'/x',dependencies:{credentials:()=>credential(),fetch:async()=>new Response('',{status:503}),diagnostic:value=>diagnostics.push(value)}}));assert.equal(diagnostics[0].status,503)});
test('only GET is exposed and sent',async()=>{let method='';await oandaReadRequest({operation:'get_only',endpointTemplate:'/x',mode:'demo',buildPath:()=>'/x',dependencies:{credentials:()=>credential(),fetch:async(_u,i)=>{method=String(i?.method);return new Response('{}')},diagnostic:()=>{}}});assert.equal(method,'GET')});
test('boundary jitter is deterministic, bounded, and below the M5 cycle',()=>{const first=workerScanJitterMs('EUR/USD');assert.equal(first,workerScanJitterMs('EUR/USD'));assert.ok(first>=0&&first<=1_500&&first<300_000)});
test('collector jitter spreads pair requests across a wider bounded window',()=>{const values=['EUR/USD','GBP/JPY','NZD/USD','USD/CHF'].map(pair=>candleCollectorJitterMs(pair));assert.ok(values.every(value=>value>=0&&value<=15_000));assert.ok(new Set(values).size>1);assert.equal(values[0],candleCollectorJitterMs('EUR/USD'))});
test('pair timeframe reads are serialized instead of bursting concurrently',async()=>{let active=0,peak=0;const order:string[]=[];const results=await runSequentially(['M15','M5','M1'],async timeframe=>{active++;peak=Math.max(peak,active);order.push(`start:${timeframe}`);await new Promise(resolve=>setTimeout(resolve,1));order.push(`end:${timeframe}`);active--;return timeframe});assert.equal(peak,1);assert.deepEqual(results,['M15','M5','M1']);assert.deepEqual(order,['start:M15','end:M15','start:M5','end:M5','start:M1','end:M1'])});
