import {useCallback,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import styled from 'styled-components';
import {forexPairs} from '../utils/constants';
import {calculateScoreRisk,RISK_PROFILES,type RiskProfile} from '../utils/dynamicRisk';

const Page=styled.div`width:min(1380px,calc(100% - 30px));margin:0 auto 80px;color:#eef3ff;font-family:Inter,system-ui,sans-serif;`;
const Hero=styled.section`padding:24px;border:1px solid #2b3240;border-radius:24px;background:radial-gradient(circle at 80% 0,#35204c 0,transparent 34%),linear-gradient(145deg,#151922,#0b0e13);box-shadow:0 24px 80px #0009;`;
const Kicker=styled.div`color:#ef9cff;font-size:.72rem;font-weight:900;letter-spacing:.16em;text-transform:uppercase;`;
const Title=styled.h1`font-size:clamp(2rem,5vw,4.4rem);line-height:.95;margin:10px 0;background:linear-gradient(90deg,#fff,#f6a9ff,#74e7ff);-webkit-background-clip:text;color:transparent;`;
const Sub=styled.p`color:#99a5b8;max-width:800px;line-height:1.55;margin:0;`;
const Controls=styled.div`display:grid;grid-template-columns:1.5fr .6fr .6fr auto;gap:12px;margin-top:22px;@media(max-width:850px){grid-template-columns:1fr 1fr}`;
const Field=styled.label`display:grid;gap:6px;color:#8e99aa;font-size:.7rem;text-transform:uppercase;font-weight:800;input,select{border:1px solid #343c4a;background:#0c1016;color:#fff;border-radius:12px;padding:11px 12px;outline:none}`;
const Button=styled.button`border:1px solid #9b49c8;background:linear-gradient(135deg,#6d2399,#c23cd9);color:#fff;border-radius:13px;padding:11px 18px;font-weight:900;cursor:pointer;box-shadow:0 0 28px #a63ac444;&:disabled{opacity:.45;cursor:not-allowed}`;
const CancelButton=styled(Button)`border-color:#ff6678;background:linear-gradient(135deg,#6f1e35,#b92f50);box-shadow:0 0 28px #ff426633;`;
const PairGrid=styled.div`display:flex;gap:8px;flex-wrap:wrap;margin-top:14px;`;
const Pair=styled.button<{$on:boolean}>`border:1px solid ${p=>p.$on?'#34d995':'#323946'};background:${p=>p.$on?'#103b2a':'#11151c'};color:${p=>p.$on?'#76ffc0':'#7f8998'};padding:8px 11px;border-radius:999px;cursor:pointer;font-weight:800;font-size:.72rem;`;
const Grid=styled.div`display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:16px;@media(max-width:850px){grid-template-columns:repeat(2,1fr)}`;
const Card=styled.div`border:1px solid #2d3542;background:#10141b;border-radius:18px;padding:17px;box-shadow:inset 0 1px #ffffff08;`;
const Metric=styled.div`font-size:1.85rem;font-weight:950;color:#fff;margin-top:6px;`;
const Label=styled.div`font-size:.66rem;text-transform:uppercase;letter-spacing:.12em;color:#7f8a9c;font-weight:850;`;
const Progress=styled.div`height:7px;margin-top:10px;border-radius:99px;background:#252b36;overflow:hidden;span{display:block;height:100%;background:linear-gradient(90deg,#e05cff,#55e8c2);transition:width .35s ease}`;
const MoneyLab=styled.section`margin-top:16px;padding:20px;border:1px solid #315243;border-radius:20px;background:radial-gradient(circle at 90% 0,#174d3b66,transparent 34%),linear-gradient(145deg,#101820,#0b1015);`;
const MoneyControls=styled.div`display:grid;grid-template-columns:repeat(3,minmax(150px,1fr));gap:12px;margin-top:16px;@media(max-width:800px){grid-template-columns:1fr 1fr}`;
const MoneyGrid=styled.div`display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-top:14px;@media(max-width:1050px){grid-template-columns:repeat(3,1fr)}@media(max-width:600px){grid-template-columns:repeat(2,1fr)}`;
const MoneyNote=styled.p`margin:12px 0 0;color:#7f8e99;font-size:.7rem;line-height:1.5;`;
const Section=styled.section`margin-top:16px;border:1px solid #29313d;background:#0c1016;border-radius:20px;overflow:hidden;`;
const Head=styled.div`display:flex;justify-content:space-between;gap:12px;align-items:center;padding:16px 18px;border-bottom:1px solid #28303b;h2{font-size:.95rem;margin:0}.muted{color:#758094;font-size:.72rem}`;
const Table=styled.div`overflow:auto;max-height:520px;table{width:100%;border-collapse:collapse;min-width:850px}th,td{padding:11px 14px;border-bottom:1px solid #222a34;text-align:left;font-size:.72rem}th{position:sticky;top:0;background:#151a22;color:#7e8999;text-transform:uppercase}.win{color:#58ee9b;font-weight:900}.loss{color:#ff6678;font-weight:900}`;
const Feed=styled.div`max-height:390px;overflow:auto;display:flex;flex-direction:column;`;
const Event=styled.div`display:grid;grid-template-columns:9px 80px 90px 1fr;gap:10px;padding:11px 16px;border-bottom:1px solid #222933;align-items:start;font-size:.72rem;color:#bdc5d1;.dot{width:8px;height:8px;border-radius:50%;background:#e45bff;box-shadow:0 0 12px #e45bff}.time,.pair{color:#687487}.message{line-height:1.4}`;
const ReplayLink=styled(Link)`display:inline-flex;border:1px solid #a763db;background:#2d153d;color:#f1ceff;border-radius:7px;padding:5px 8px;text-decoration:none;font-weight:850;white-space:nowrap;`;
const DeleteButton=styled.button`border:1px solid #7a3443;background:#35151d;color:#ff8797;border-radius:8px;padding:5px 8px;font-size:.66rem;font-weight:850;cursor:pointer;white-space:nowrap;&:hover{border-color:#ff6678;background:#571f2d;color:#fff}&:disabled{opacity:.45;cursor:not-allowed}`;
const PairCount=styled.span`position:relative;display:inline-flex;align-items:center;justify-content:center;min-width:30px;padding:4px 8px;border:1px solid #36d6a1;background:#10372d;color:#7dffd0;border-radius:999px;font-weight:900;cursor:help;outline:none;&:hover>span,&:focus-visible>span{opacity:1;visibility:visible;transform:translate(-50%,0)}>`;
const PairTip=styled.span`position:absolute;z-index:20;left:50%;bottom:calc(100% + 8px);width:max-content;max-width:310px;padding:9px 11px;border:1px solid #485365;border-radius:10px;background:#111720;color:#e8eef8;box-shadow:0 12px 30px #000b;line-height:1.6;white-space:normal;opacity:0;visibility:hidden;transform:translate(-50%,5px);transition:.15s ease;pointer-events:none;strong{display:block;color:#71efc0;font-size:.62rem;letter-spacing:.08em;text-transform:uppercase}.list{display:block;font-weight:750}`;

type RunConfig={minimumScore:number;lookbackDays:number;pairs:string[];startingBalance?:number;leverage?:number;riskProfile?:RiskProfile;protectedWinR?:number};
type Run={id:string;status:string;label:string;createdAt:string;progressPair?:string;progressDone:number;progressTotal:number;progressStage?:string;progressPercent?:number;heartbeatAt?:string;totalTrades:number;wins:number;losses:number;error?:string;config:RunConfig};
type LeaderboardRow={runId:string;label:string;createdAt:string;pair:string;trades:number;wins:number;losses:number;winRate:number;averageScore:number;protectedWins:number;config:RunConfig};
type Dashboard={runs:Run[];selectedRunId:string;trades:Array<Record<string,any>>;pairs:Array<Record<string,any>>;leaderboard:LeaderboardRow[];events:Array<Record<string,any>>};

export default function Backtesting(){
 const [data,setData]=useState<Dashboard|null>(null),[selected,setSelected]=useState<string[]>([...forexPairs]);
 const [label,setLabel]=useState('20-point baseline'),[minimumScore,setMinimumScore]=useState(14),[lookbackDays,setLookbackDays]=useState(730),[busy,setBusy]=useState(false),[deletingId,setDeletingId]=useState(''),[error,setError]=useState('');
 const [startingBalance,setStartingBalance]=useState(1000),[leverage,setLeverage]=useState(30),[riskProfile,setProjectionRiskProfile]=useState<RiskProfile>('default');
 const load=useCallback(async(runId?:string)=>{try{const r=await fetch(`/api/backtests${runId?`?runId=${runId}`:''}`,{cache:'no-store'});if(!r.ok)throw new Error((await r.json()).error);setData(await r.json());setError('')}catch(e){setError((e as Error).message)}},[]);
 const selectSnapshot=(runId:string,config:Run['config'],snapshotLabel:string)=>{setSelected(Array.isArray(config.pairs)?[...config.pairs]:[]);setMinimumScore(config.minimumScore);setLookbackDays(config.lookbackDays);setStartingBalance(config.startingBalance??1000);setLeverage(config.leverage??30);setProjectionRiskProfile(config.riskProfile??'default');setLabel(`${snapshotLabel} · rerun`);void load(runId)};
 const active=data?.runs.some(run=>run.status==='running'||run.status==='queued')??false;
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!data?.selectedRunId)return;const id=setInterval(()=>load(data.selectedRunId),active?2000:10000);return()=>clearInterval(id)},[load,data?.selectedRunId,active]);
 const run=async()=>{setBusy(true);try{const r=await fetch('/api/backtests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pairs:selected,label,minimumScore,lookbackDays,startingBalance,leverage,riskProfile})});const body=await r.json();if(!r.ok)throw new Error(body.error);await load(body.id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const current=data?.runs.find(item=>item.id===data.selectedRunId)??data?.runs[0];
 const cancel=async()=>{if(!current)return;setBusy(true);try{const r=await fetch(`/api/backtests?runId=${current.id}`,{method:'DELETE'});const body=await r.json();if(!r.ok)throw new Error(body.error);await load(current.id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const removeRun=async(runId:string,label:string)=>{if(!window.confirm(`Permanently delete "${label}" and all of its recorded trades and logs? This cannot be undone.`))return;setDeletingId(runId);try{const r=await fetch(`/api/backtests?runId=${encodeURIComponent(runId)}&permanent=true`,{method:'DELETE'});const body=await r.json();if(!r.ok)throw new Error(body.error);await load(data?.selectedRunId===runId?undefined:data?.selectedRunId);setError('')}catch(e){setError((e as Error).message)}finally{setDeletingId('')}};
 const winRate=current?.totalTrades?Math.round(current.wins/current.totalTrades*1000)/10:0;
 const running=current?.status==='running'||current?.status==='queued';
 const progress=Math.max(0,Math.min(100,Number(current?.progressPercent??0)));
 const projection=useMemo(()=>{
   const initial=Math.max(1,Number(startingBalance)||1);let equity=initial,peak=initial,maxDrawdown=0,totalRisked=0,marginCapped=0;
   const byPair=new Map<string,{pair:string,trades:number,wins:number,losses:number,net:number}>();
   const trades=[...(data?.trades??[])].sort((a,b)=>Number(a.confirmationTime)-Number(b.confirmationTime));
   for(const trade of trades){
     const score=Number(trade.score??current?.config.minimumScore??14);const risk=calculateScoreRisk(score,current?.config.minimumScore??14,riskProfile);
     const desiredRisk=equity*(risk.riskPercentage/100);const entry=Math.abs(Number(trade.entry));const stopDistance=Math.abs(Number(trade.entry)-Number(trade.stopLoss));
     const stopFraction=entry>0?stopDistance/entry:0;const leverageRiskCap=stopFraction>0?equity*leverage*stopFraction:desiredRisk;
     const riskAmount=Math.max(0,Math.min(desiredRisk,leverageRiskCap));if(riskAmount+1e-9<desiredRisk)marginCapped+=1;
     const rMultiple=trade.realizedR==null?(trade.outcome==='WIN'?0:-1):Number(trade.realizedR);const pnl=riskAmount*rMultiple;equity=Math.max(0,equity+pnl);totalRisked+=riskAmount;
     peak=Math.max(peak,equity);if(peak>0)maxDrawdown=Math.max(maxDrawdown,(peak-equity)/peak*100);
     const row=byPair.get(trade.pair)??{pair:String(trade.pair),trades:0,wins:0,losses:0,net:0};row.trades+=1;row.wins+=trade.outcome==='WIN'?1:0;row.losses+=trade.outcome==='LOSS'?1:0;row.net+=pnl;byPair.set(trade.pair,row);
   }
   return {initial,ending:equity,net:equity-initial,returnPercent:(equity-initial)/initial*100,maxDrawdown,totalRisked,marginCapped,byPair:[...byPair.values()].sort((a,b)=>b.net-a.net)};
 },[current?.config.minimumScore,data?.trades,leverage,riskProfile,startingBalance]);
 const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(value);
 return <Page><Hero><Kicker>Goldilocks research arcade</Kicker><Title>Backtest Candy Lab</Title><Sub>Run the exact M15 trend -&gt; M5 zone -&gt; M1 confirmation strategy across preserved history. Every run is a permanent tweak snapshot; +1R is immediately recorded as a protected win.</Sub><Controls><Field>Version / tweak label<input value={label} onChange={e=>setLabel(e.target.value)}/></Field><Field>Minimum score<select value={minimumScore} onChange={e=>setMinimumScore(Number(e.target.value))}>{Array.from({length:21},(_,i)=><option key={i}>{i}</option>)}</select></Field><Field>Lookback<select value={lookbackDays} onChange={e=>setLookbackDays(Number(e.target.value))}><option value={90}>90 days</option><option value={365}>1 year</option><option value={730}>2 years</option></select></Field>{running?<CancelButton disabled={busy} onClick={cancel}>{busy?'Stopping...':'Cancel run'}</CancelButton>:<Button disabled={busy||!selected.length||active} onClick={run}>{busy?'Launching...':'Run backtest'}</Button>}</Controls><PairGrid><Pair $on={selected.length===forexPairs.length} onClick={()=>setSelected(selected.length===forexPairs.length?[]:[...forexPairs])}>ALL PAIRS</Pair>{forexPairs.map(pair=><Pair key={pair} $on={selected.includes(pair)} onClick={()=>setSelected(items=>items.includes(pair)?items.filter(x=>x!==pair):[...items,pair])}>{pair}</Pair>)}</PairGrid>{error&&<p style={{color:'#ff7587'}}>{error}</p>}</Hero>
 <Grid><Card><Label>Trades</Label><Metric>{current?.totalTrades??0}</Metric></Card><Card><Label>Protected wins</Label><Metric style={{color:'#60f0a2'}}>{current?.wins??0}</Metric></Card><Card><Label>Total win rate</Label><Metric>{winRate}%</Metric></Card><Card><Label>Status</Label><Metric style={{fontSize:'1.05rem',color:current?.status==='failed'||current?.status==='cancelled'?'#ff6678':'#eaa3ff'}}>{current?.status?.toUpperCase()??'READY'}</Metric>{running&&<><div style={{color:'#7d899b',fontSize:12,marginTop:8}}>{current?.progressDone}/{current?.progressTotal} - {current?.progressPair??'preparing'}<br/>{current?.progressStage??'working'} - {progress.toFixed(1)}% overall</div><Progress><span style={{width:`${progress}%`}}/></Progress></>}</Card></Grid>
 <MoneyLab><Head style={{padding:0,border:0}}><div><h2>Projected account money</h2><span className="muted">Score-powered compound-risk simulation for the selected tweak</span></div></Head><MoneyControls><Field>Starting account (USD)<input type="number" min="1" step="100" value={startingBalance} onChange={e=>setStartingBalance(Number(e.target.value))}/></Field><Field>Dynamic risk profile<select value={riskProfile} onChange={e=>setProjectionRiskProfile(e.target.value as RiskProfile)}>{(Object.keys(RISK_PROFILES) as RiskProfile[]).map(profile=><option key={profile} value={profile}>{RISK_PROFILES[profile].label} · {RISK_PROFILES[profile].minimumRisk}%–{RISK_PROFILES[profile].maximumRisk}%</option>)}</select></Field><Field>Account leverage / margin<select value={leverage} onChange={e=>setLeverage(Number(e.target.value))}><option value={10}>10:1</option><option value={20}>20:1</option><option value={30}>30:1</option><option value={50}>50:1</option></select></Field></MoneyControls><MoneyGrid><Card><Label>Ending balance</Label><Metric style={{fontSize:'1.35rem'}}>{money(projection.ending)}</Metric></Card><Card><Label>Net profit / loss</Label><Metric style={{fontSize:'1.35rem',color:projection.net>=0?'#60f0a2':'#ff6678'}}>{money(projection.net)}</Metric></Card><Card><Label>Account return</Label><Metric style={{fontSize:'1.35rem',color:projection.returnPercent>=0?'#60f0a2':'#ff6678'}}>{projection.returnPercent.toFixed(2)}%</Metric></Card><Card><Label>Max drawdown</Label><Metric style={{fontSize:'1.35rem',color:'#ffb65c'}}>{projection.maxDrawdown.toFixed(2)}%</Metric></Card><Card><Label>Total risk allocated</Label><Metric style={{fontSize:'1.35rem'}}>{money(projection.totalRisked)}</Metric></Card><Card><Label>Margin-capped trades</Label><Metric style={{fontSize:'1.35rem'}}>{projection.marginCapped}</Metric></Card></MoneyGrid><MoneyNote>New runs use score-tiered exits: 14–15 closes fully at 2R; 16–17 banks 75% at 2R and runs 25%; 18–20 banks 50% and runs 50%. After 2R, runner protection moves to +1R and the research target is 4R. Ending balance uses each trade’s blended realized R. Older runs should be rerun to receive runner outcomes.</MoneyNote>{projection.byPair.length>0&&<Table style={{marginTop:14,maxHeight:260}}><table><thead><tr><th>Pair</th><th>Trades</th><th>Wins</th><th>Losses</th><th>Projected net P/L</th></tr></thead><tbody>{projection.byPair.map(row=><tr key={row.pair}><td>{row.pair}</td><td>{row.trades}</td><td className="win">{row.wins}</td><td className="loss">{row.losses}</td><td className={row.net>=0?'win':'loss'}>{money(row.net)}</td></tr>)}</tbody></table></Table>}</MoneyLab>
 <Section><Head><h2>Tweak history</h2><span className="muted">Every run preserves its settings and outcomes · click to restore settings</span></Head><Table><table><thead><tr><th>Label</th><th>Date</th><th>Pairs</th><th>Min score</th><th>Trades</th><th>Wins</th><th>Win rate</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data?.runs.map(item=>{const pairs=Array.isArray(item.config?.pairs)?item.config.pairs:[];const pairText=pairs.length?pairs.join(', '):'Pair details were not stored for this older run';const activeRun=item.status==='running'||item.status==='queued';return <tr key={item.id} onClick={()=>selectSnapshot(item.id,item.config,item.label)} style={{cursor:'pointer',background:item.id===data.selectedRunId?'#25152f':''}}><td>{item.label}</td><td>{new Date(item.createdAt).toLocaleString()}</td><td><PairCount tabIndex={0} title={pairText} aria-label={`${pairs.length} pairs: ${pairText}`}>{pairs.length}<PairTip><strong>Pairs in this tweak</strong><span className="list">{pairText}</span></PairTip></PairCount></td><td>{item.config.minimumScore}/20</td><td>{item.totalTrades}</td><td>{item.wins}</td><td>{item.totalTrades?(item.wins/item.totalTrades*100).toFixed(1):0}%</td><td>{item.status}</td><td><DeleteButton disabled={activeRun||deletingId===item.id} title={activeRun?'Cancel the run before deleting it':'Delete this tweak, its trades, and logs'} onClick={event=>{event.stopPropagation();void removeRun(item.id,item.label)}}>{deletingId===item.id?'Deleting…':'Delete'}</DeleteButton></td></tr>})}</tbody></table></Table></Section>
 <Section><Head><h2>All-tweak pair leaderboard</h2><span className="muted">Completed tweak + pair results · highest win rate first · click to reproduce</span></Head><Table><table><thead><tr><th>#</th><th>Pair</th><th>Tweak</th><th>Run date</th><th>Min score</th><th>Lookback</th><th>Trades</th><th>Wins</th><th>Losses</th><th>Win rate</th><th>Avg score</th><th>1R protected</th><th>Actions</th></tr></thead><tbody>{data?.leaderboard.map((row,index)=>{const runPairs=Array.isArray(row.config?.pairs)?row.config.pairs:[];const pairText=runPairs.length?runPairs.join(', '):'Pair details unavailable';return <tr key={`${row.runId}:${row.pair}`} onClick={()=>selectSnapshot(row.runId,row.config,row.label)} style={{cursor:'pointer',background:row.runId===data.selectedRunId?'#152c29':''}} title={`Restore ${row.label} settings and results`}><td>{index+1}</td><td><strong>{row.pair}</strong></td><td>{row.label}<br/><PairCount tabIndex={0} title={pairText} aria-label={`${runPairs.length} run pairs: ${pairText}`}>{runPairs.length} pairs<PairTip><strong>Full run universe</strong><span className="list">{pairText}</span></PairTip></PairCount></td><td>{new Date(row.createdAt).toLocaleDateString()}</td><td>{row.config.minimumScore}/20</td><td>{row.config.lookbackDays} days</td><td>{row.trades}</td><td className="win">{row.wins}</td><td className="loss">{row.losses}</td><td className="win">{row.winRate}%</td><td>{row.averageScore}/20</td><td>{row.protectedWins}</td><td><DeleteButton disabled={deletingId===row.runId} title="Delete this entire tweak and all pair results" onClick={event=>{event.stopPropagation();void removeRun(row.runId,row.label)}}>{deletingId===row.runId?'Deleting…':'Delete tweak'}</DeleteButton></td></tr>})}</tbody></table></Table></Section>
 <Section><Head><h2>Recorded trades</h2><span className="muted">Open any trade in Strategy Lab for chart replay</span></Head><Table><table><thead><tr><th>Time</th><th>Pair</th><th>Side</th><th>Zone</th><th>Score</th><th>Prior touches</th><th>Penetration</th><th>Available R</th><th>MTF</th><th>Result</th><th>Replay</th></tr></thead><tbody>{data?.trades.map(t=>{const result=t.realizedR==null?(t.outcome==='WIN'?'Legacy protected · final unknown':'-1R stop'):t.exitReason==='runner_target'?`${Number(t.realizedR).toFixed(2)}R · runner reached 4R`:t.exitReason==='runner_stop'?`${Number(t.realizedR).toFixed(2)}R · runner protected at 1R`:t.exitReason==='runner_open'?`${Number(t.realizedR).toFixed(2)}R floor · runner open at data end`:t.exitReason==='target'?'+2R target':t.exitReason==='break_even'?'0R break-even':'-1R stop';return <tr key={t.id}><td>{new Date(t.confirmationTime*1000).toLocaleString()}</td><td>{t.pair}</td><td>{t.direction}</td><td>{t.zoneKind}</td><td>{t.score}/20</td><td>{t.priorTouches}</td><td>{(t.maxPenetration*100).toFixed(1)}%</td><td>{t.availableRrr==null?'unlimited':Number(t.availableRrr).toFixed(2)}R</td><td>{t.confluenceCount}/3</td><td className={t.outcome.toLowerCase()}>{t.outcome} · {result}</td><td><ReplayLink href={`/strategy-lab?pair=${encodeURIComponent(t.pair)}&timeframe=M5&tradeTime=${t.confirmationTime}`}>View chart</ReplayLink></td></tr>})}</tbody></table></Table></Section>
 <Section><Head><h2>Backtest candylog</h2><span className="muted">Newest steps first</span></Head><Feed>{data?.events.map(e=><Event key={e.id}><span className="dot"/><span className="time">{new Date(e.createdAt).toLocaleTimeString()}</span><span className="pair">{e.pair??'RUN'}</span><span className="message">{e.message}</span></Event>)}</Feed></Section>
 </Page>
}
