import {useCallback,useEffect,useMemo,useState} from 'react';
import styled from 'styled-components';
import {forexPairs} from '../utils/constants';

const Page=styled.div`width:min(1380px,calc(100% - 30px));margin:0 auto 80px;color:#eef3ff;font-family:Inter,system-ui,sans-serif;`;
const Hero=styled.section`padding:24px;border:1px solid #2b3240;border-radius:24px;background:radial-gradient(circle at 80% 0,#35204c 0,transparent 34%),linear-gradient(145deg,#151922,#0b0e13);box-shadow:0 24px 80px #0009;`;
const Kicker=styled.div`color:#ef9cff;font-size:.72rem;font-weight:900;letter-spacing:.16em;text-transform:uppercase;`;
const Title=styled.h1`font-size:clamp(2rem,5vw,4.4rem);line-height:.95;margin:10px 0;background:linear-gradient(90deg,#fff,#f6a9ff,#74e7ff);-webkit-background-clip:text;color:transparent;`;
const Sub=styled.p`color:#99a5b8;max-width:800px;line-height:1.55;margin:0;`;
const Controls=styled.div`display:grid;grid-template-columns:1.5fr .6fr .6fr auto;gap:12px;margin-top:22px;@media(max-width:850px){grid-template-columns:1fr 1fr}`;
const Field=styled.label`display:grid;gap:6px;color:#8e99aa;font-size:.7rem;text-transform:uppercase;font-weight:800;input,select{border:1px solid #343c4a;background:#0c1016;color:#fff;border-radius:12px;padding:11px 12px;outline:none}`;
const Button=styled.button`border:1px solid #9b49c8;background:linear-gradient(135deg,#6d2399,#c23cd9);color:#fff;border-radius:13px;padding:11px 18px;font-weight:900;cursor:pointer;box-shadow:0 0 28px #a63ac444;&:disabled{opacity:.45;cursor:not-allowed}`;
const CancelButton=styled(Button)`border-color:#ff6678;background:linear-gradient(135deg,#6f1e35,#b92f50);box-shadow:0 0 28px #ff426633;`;
const PairGrid=styled.div`display:flex;gap:8px;flex-wrap:wrap;margin-top:14px;`;
const Pair=styled.button<{$on:boolean}>`border:1px solid ${p=>p.$on?'#34d995':'#323946'};background:${p=>p.$on?'#103b2a':'#11151c'};color:${p=>p.$on?'#76ffc0':'#7f8998'};padding:8px 11px;border-radius:999px;cursor:pointer;font-weight:800;font-size:.72rem;`;
const Grid=styled.div`display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:16px;@media(max-width:850px){grid-template-columns:repeat(2,1fr)}`;
const Card=styled.div`border:1px solid #2d3542;background:#10141b;border-radius:18px;padding:17px;box-shadow:inset 0 1px #ffffff08;`;
const Metric=styled.div`font-size:1.85rem;font-weight:950;color:#fff;margin-top:6px;`;
const Label=styled.div`font-size:.66rem;text-transform:uppercase;letter-spacing:.12em;color:#7f8a9c;font-weight:850;`;
const Progress=styled.div`height:7px;margin-top:10px;border-radius:99px;background:#252b36;overflow:hidden;span{display:block;height:100%;background:linear-gradient(90deg,#e05cff,#55e8c2);transition:width .35s ease}`;
const Section=styled.section`margin-top:16px;border:1px solid #29313d;background:#0c1016;border-radius:20px;overflow:hidden;`;
const Head=styled.div`display:flex;justify-content:space-between;gap:12px;align-items:center;padding:16px 18px;border-bottom:1px solid #28303b;h2{font-size:.95rem;margin:0}.muted{color:#758094;font-size:.72rem}`;
const Table=styled.div`overflow:auto;max-height:520px;table{width:100%;border-collapse:collapse;min-width:850px}th,td{padding:11px 14px;border-bottom:1px solid #222a34;text-align:left;font-size:.72rem}th{position:sticky;top:0;background:#151a22;color:#7e8999;text-transform:uppercase}.win{color:#58ee9b;font-weight:900}.loss{color:#ff6678;font-weight:900}`;
const Feed=styled.div`max-height:390px;overflow:auto;display:flex;flex-direction:column;`;
const Event=styled.div`display:grid;grid-template-columns:9px 80px 90px 1fr;gap:10px;padding:11px 16px;border-bottom:1px solid #222933;align-items:start;font-size:.72rem;color:#bdc5d1;.dot{width:8px;height:8px;border-radius:50%;background:#e45bff;box-shadow:0 0 12px #e45bff}.time,.pair{color:#687487}.message{line-height:1.4}`;

type Run={id:string;status:string;label:string;createdAt:string;progressPair?:string;progressDone:number;progressTotal:number;progressStage?:string;progressPercent?:number;heartbeatAt?:string;totalTrades:number;wins:number;losses:number;error?:string;config:{minimumScore:number;lookbackDays:number;pairs:string[]}};
type Dashboard={runs:Run[];selectedRunId:string;trades:Array<Record<string,any>>;pairs:Array<Record<string,any>>;events:Array<Record<string,any>>};

export default function Backtesting(){
 const [data,setData]=useState<Dashboard|null>(null),[selected,setSelected]=useState<string[]>([...forexPairs]);
 const [label,setLabel]=useState('20-point baseline'),[minimumScore,setMinimumScore]=useState(14),[lookbackDays,setLookbackDays]=useState(730),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async(runId?:string)=>{try{const r=await fetch(`/api/backtests${runId?`?runId=${runId}`:''}`,{cache:'no-store'});if(!r.ok)throw new Error((await r.json()).error);setData(await r.json());setError('')}catch(e){setError((e as Error).message)}},[]);
 const active=data?.runs.some(run=>run.status==='running'||run.status==='queued')??false;
 useEffect(()=>{load();const id=setInterval(()=>load(data?.selectedRunId),active?2000:10000);return()=>clearInterval(id)},[load,data?.selectedRunId,active]);
 const run=async()=>{setBusy(true);try{const r=await fetch('/api/backtests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pairs:selected,label,minimumScore,lookbackDays})});const body=await r.json();if(!r.ok)throw new Error(body.error);await load(body.id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const current=data?.runs.find(item=>item.id===data.selectedRunId)??data?.runs[0];
 const cancel=async()=>{if(!current)return;setBusy(true);try{const r=await fetch(`/api/backtests?runId=${current.id}`,{method:'DELETE'});const body=await r.json();if(!r.ok)throw new Error(body.error);await load(current.id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const winRate=current?.totalTrades?Math.round(current.wins/current.totalTrades*1000)/10:0;
 const protectedWins=useMemo(()=>data?.trades.filter(t=>t.exitReason==='one_r_protected').length??0,[data]);
 const running=current?.status==='running'||current?.status==='queued';
 const progress=Math.max(0,Math.min(100,Number(current?.progressPercent??0)));
 return <Page><Hero><Kicker>Goldilocks research arcade</Kicker><Title>Backtest Candy Lab</Title><Sub>Run the exact M15 trend -&gt; M5 zone -&gt; M1 confirmation strategy across preserved history. Every run is a permanent tweak snapshot; +1R is immediately recorded as a protected win.</Sub><Controls><Field>Version / tweak label<input value={label} onChange={e=>setLabel(e.target.value)}/></Field><Field>Minimum score<select value={minimumScore} onChange={e=>setMinimumScore(Number(e.target.value))}>{Array.from({length:21},(_,i)=><option key={i}>{i}</option>)}</select></Field><Field>Lookback<select value={lookbackDays} onChange={e=>setLookbackDays(Number(e.target.value))}><option value={90}>90 days</option><option value={365}>1 year</option><option value={730}>2 years</option></select></Field>{running?<CancelButton disabled={busy} onClick={cancel}>{busy?'Stopping...':'Cancel run'}</CancelButton>:<Button disabled={busy||!selected.length||active} onClick={run}>{busy?'Launching...':'Run backtest'}</Button>}</Controls><PairGrid><Pair $on={selected.length===forexPairs.length} onClick={()=>setSelected(selected.length===forexPairs.length?[]:[...forexPairs])}>ALL PAIRS</Pair>{forexPairs.map(pair=><Pair key={pair} $on={selected.includes(pair)} onClick={()=>setSelected(items=>items.includes(pair)?items.filter(x=>x!==pair):[...items,pair])}>{pair}</Pair>)}</PairGrid>{error&&<p style={{color:'#ff7587'}}>{error}</p>}</Hero>
 <Grid><Card><Label>Trades</Label><Metric>{current?.totalTrades??0}</Metric></Card><Card><Label>Protected wins</Label><Metric style={{color:'#60f0a2'}}>{current?.wins??0}</Metric></Card><Card><Label>Total win rate</Label><Metric>{winRate}%</Metric></Card><Card><Label>Status</Label><Metric style={{fontSize:'1.05rem',color:current?.status==='failed'||current?.status==='cancelled'?'#ff6678':'#eaa3ff'}}>{current?.status?.toUpperCase()??'READY'}</Metric>{running&&<><div style={{color:'#7d899b',fontSize:12,marginTop:8}}>{current?.progressDone}/{current?.progressTotal} - {current?.progressPair??'preparing'}<br/>{current?.progressStage??'working'} - {progress.toFixed(1)}% overall</div><Progress><span style={{width:`${progress}%`}}/></Progress></>}</Card></Grid>
 <Section><Head><h2>Tweak history</h2><span className="muted">Every run preserves its settings and outcomes</span></Head><Table><table><thead><tr><th>Label</th><th>Date</th><th>Pairs</th><th>Min score</th><th>Trades</th><th>Wins</th><th>Win rate</th><th>Status</th></tr></thead><tbody>{data?.runs.map(item=><tr key={item.id} onClick={()=>load(item.id)} style={{cursor:'pointer',background:item.id===data.selectedRunId?'#25152f':''}}><td>{item.label}</td><td>{new Date(item.createdAt).toLocaleString()}</td><td>{item.config.pairs.length}</td><td>{item.config.minimumScore}/20</td><td>{item.totalTrades}</td><td>{item.wins}</td><td>{item.totalTrades?(item.wins/item.totalTrades*100).toFixed(1):0}%</td><td>{item.status}</td></tr>)}</tbody></table></Table></Section>
 <Section><Head><h2>Pair scoreboard</h2><span className="muted">{protectedWins} loaded protected-win records</span></Head><Table><table><thead><tr><th>Pair</th><th>Trades</th><th>Wins</th><th>Losses</th><th>Win rate</th><th>Avg score</th><th>1R protected</th></tr></thead><tbody>{data?.pairs.map(row=><tr key={row.pair}><td>{row.pair}</td><td>{row.trades}</td><td className="win">{row.wins}</td><td className="loss">{row.losses}</td><td>{row.winRate}%</td><td>{row.averageScore}/20</td><td>{row.protectedWins}</td></tr>)}</tbody></table></Table></Section>
 <Section><Head><h2>Recorded trades</h2><span className="muted">One open trade per pair enforced chronologically</span></Head><Table><table><thead><tr><th>Time</th><th>Pair</th><th>Side</th><th>Zone</th><th>Score</th><th>Prior touches</th><th>Penetration</th><th>Available R</th><th>MTF</th><th>Result</th></tr></thead><tbody>{data?.trades.map(t=><tr key={t.id}><td>{new Date(t.confirmationTime*1000).toLocaleString()}</td><td>{t.pair}</td><td>{t.direction}</td><td>{t.zoneKind}</td><td>{t.score}/20</td><td>{t.priorTouches}</td><td>{(t.maxPenetration*100).toFixed(1)}%</td><td>{t.availableRrr==null?'unlimited':Number(t.availableRrr).toFixed(2)}R</td><td>{t.confluenceCount}/3</td><td className={t.outcome.toLowerCase()}>{t.outcome} - {t.exitReason==='one_r_protected'?'+1R protected':'SL'}</td></tr>)}</tbody></table></Table></Section>
 <Section><Head><h2>Backtest candylog</h2><span className="muted">Newest steps first</span></Head><Feed>{data?.events.map(e=><Event key={e.id}><span className="dot"/><span className="time">{new Date(e.createdAt).toLocaleTimeString()}</span><span className="pair">{e.pair??'RUN'}</span><span className="message">{e.message}</span></Event>)}</Feed></Section>
 </Page>
}
