import dynamic from 'next/dynamic';
import { useCallback, useState } from 'react';
import styled from 'styled-components';
import { forexPairs } from '../utils/constants';
import type { GoldilocksDetection, StrategyCandle, SwingLeg, TradeRunwayCheck } from '../utils/goldilocksStrategy';

const StrategyLabChart=dynamic(()=>import('../components/StrategyLabChart'),{ssr:false,loading:()=> <div style={{height:540,color:'#778293',display:'grid',placeItems:'center'}}>Loading chart engine…</div>});
const Page=styled.div`width:min(1300px,calc(100% - 32px));margin:0 auto 60px;color:#f3f5f8;font-family:Inter,system-ui,sans-serif;`;
const Header=styled.div`display:flex;justify-content:space-between;gap:16px;align-items:flex-end;flex-wrap:wrap;margin-bottom:18px;`;
const Title=styled.h1`font-size:clamp(1.7rem,4vw,2.8rem);letter-spacing:-.04em;margin:0 0 6px;`;
const Copy=styled.p`color:#8b95a5;margin:0;max-width:760px;`;
const Controls=styled.div`display:flex;gap:8px;`;
const Button=styled.button<{active:boolean}>`border:1px solid ${({active})=>active?'#7f3db7':'#303642'};background:${({active})=>active?'#351447':'#15191f'};color:${({active})=>active?'#f0ccff':'#929cab'};border-radius:10px;padding:9px 13px;font-weight:800;cursor:pointer;`;
const Select=styled.select`border:1px solid #303642;background:#15191f;color:#d6dbe3;border-radius:10px;padding:9px 11px;font-weight:700;`;
const Legend=styled.div`display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:14px;@media(max-width:800px){grid-template-columns:1fr 1fr}`;
const Rule=styled.div`border:1px solid #292f39;background:#12151b;border-radius:12px;padding:12px;color:#a8b0bc;font-size:.76rem;line-height:1.45;`;
const Diagnostics=styled.div`display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:14px;@media(max-width:780px){grid-template-columns:1fr}`;
const Diagnostic=styled.div`border:1px solid #313743;background:#101319;border-radius:12px;padding:13px;color:#929cab;font-size:.75rem;line-height:1.5;strong{color:#f0d5ff}ul{margin:7px 0 0;padding-left:18px}`;
const Ledger=styled.div`margin-top:14px;border:1px solid #303642;border-radius:14px;overflow:auto;background:#0d1015;max-height:420px;table{width:100%;border-collapse:collapse;min-width:980px}th,td{padding:10px 12px;border-bottom:1px solid #252b34;text-align:left;font-size:.7rem}th{position:sticky;top:0;background:#171b22;color:#929cab;text-transform:uppercase}td{color:#cdd3dc}.win{color:#55e88b;font-weight:800}.loss{color:#ff6876;font-weight:800}`;

type HistoricalEntrySetup={zone:GoldilocksDetection['zones'][number];confirmationTimeframe:string;confirmationTime:number;confirmationCandle:StrategyCandle;runway:TradeRunwayCheck;trend:'bullish'|'bearish'|'unknown';score:{total:number;minimumScore:number;eligible:boolean;reason:string};outcome:'win'|'loss'|'open';exitReason:'target'|'stop'|'break_even'|'open';breakEvenActivated:boolean;outcomeTime?:number};
type LiveScenario={pair:string;timeframe:string;currentTrend:'bullish'|'bearish'|'unknown';fetchedAt:string;candles:StrategyCandle[];leg:SwingLeg;detection:GoldilocksDetection;zoneHistory:{zones:GoldilocksDetection['zones'];activeZones:GoldilocksDetection['zones'];activeDemand:GoldilocksDetection['zones'][number]|null;activeSupply:GoldilocksDetection['zones'][number]|null;nearestZones:GoldilocksDetection['zones'];displayZones:GoldilocksDetection['zones'];recentSwingBase:GoldilocksDetection['zones'][number]|null;recentDemandBase:GoldilocksDetection['zones'][number]|null;recentSupplyBase:GoldilocksDetection['zones'][number]|null;currentPrice:number};runwayChecks:Array<TradeRunwayCheck&{zoneId:string}>;historicalEntrySetup:HistoricalEntrySetup|null;historicalEntrySetups:HistoricalEntrySetup[];backtestCoverage:{from:number|null;to:number|null;candles:number;trendTimeframe:string;zoneTimeframe:string;confirmationTimeframe:string};swingA:{swing:string;price:number};swingB:{swing:string;price:number};swings:Array<{swing:'HH'|'HL'|'LH'|'LL';price:number;candleIndex:number;time:number}>};

export default function StrategyLab(){
  const [direction,setDirection]=useState<'bullish'|'bearish'>('bullish');
  const [source,setSource]=useState<'test'|'live'>('test');
  const [pair,setPair]=useState('EUR/USD');
  const [timeframe,setTimeframe]=useState('M5');
  const [runwayExample,setRunwayExample]=useState<'clear'|'blocked'>('blocked');
  const [live,setLive]=useState<LiveScenario|null>(null);
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState('');
  const loadLive=useCallback(async(selectedPair=pair,selectedTimeframe=timeframe)=>{setLoading(true);setError('');try{const response=await fetch(`/api/strategy-lab/zones?pair=${encodeURIComponent(selectedPair)}&timeframe=${encodeURIComponent(selectedTimeframe)}`,{cache:'no-store'});const payload=await response.json();if(!response.ok)throw new Error(payload.error??'Unable to load live zones');setLive(payload);setDirection(payload.currentTrend==='bullish'||payload.currentTrend==='bearish'?payload.currentTrend:payload.leg.direction);setSource('live')}catch(requestError){setError((requestError as Error).message)}finally{setLoading(false)}},[pair,timeframe]);
  const scenario=source==='live'&&live?{candles:live.candles,leg:live.leg,swings:live.swings,zones:live.zoneHistory.displayZones,tradeSetup:live.historicalEntrySetup}:undefined;
  return <Page><Header><div><Title>Goldilocks Zone Lab</Title><Copy>{source==='live'&&live?`${live.pair} · ${live.timeframe} · ${live.candles.length} visible candles · M15 trend: ${live.currentTrend.toUpperCase()}`:`Deterministic test candles · current trend: ${direction.toUpperCase()}.`} Zone blocks are detector-produced; the dashed line is the active swing midpoint. Base candles remain stored internally but are not highlighted.</Copy></div><Controls><Button active={source==='test'} onClick={()=>{setSource('test');setLive(null)}}>Test data</Button>{source==='test'&&<><Button active={direction==='bullish'} onClick={()=>setDirection('bullish')}>Bullish leg</Button><Button active={direction==='bearish'} onClick={()=>setDirection('bearish')}>Bearish leg</Button><Button active={runwayExample==='clear'} onClick={()=>setRunwayExample('clear')}>Clear 2:1</Button><Button active={runwayExample==='blocked'} onClick={()=>setRunwayExample('blocked')}>Blocked 2:1</Button></>}<Select aria-label="Currency pair" value={pair} onChange={event=>{setPair(event.target.value);loadLive(event.target.value,timeframe)}}>{forexPairs.map(item=><option key={item}>{item}</option>)}</Select><Select aria-label="Candle timeframe" value={timeframe} onChange={event=>{setTimeframe(event.target.value);loadLive(pair,event.target.value)}}>{['M5','M15','M30','H1','H4'].map(item=><option key={item}>{item}</option>)}</Select><Button active={source==='live'} onClick={()=>loadLive()}>{loading?'Loading…':`Load live ${timeframe}`}</Button></Controls></Header>
    {error&&<Diagnostic><strong>Live-data error</strong><br/>{error}</Diagnostic>}
    <StrategyLabChart direction={direction} scenario={scenario} runwayExample={runwayExample} pricePrecision={source==='live'&&live?(live.pair.endsWith('/JPY')?3:5):2}/>
    {live&&source==='live'&&<Diagnostics><Diagnostic><strong>Nearest active zones</strong><br/>Current price: {live.zoneHistory.currentPrice}<br/>{live.zoneHistory.nearestZones.map(zone=><span key={zone.id}>{zone.kind} {zone.side}: {zone.low}–{zone.high}<br/></span>)}<br/>{live.zoneHistory.zones.length} zones preserved internally · {live.zoneHistory.activeZones.length} active</Diagnostic>{live.detection.zones.map(zone=><Diagnostic key={zone.id}><strong>{zone.kind} {zone.side}</strong><br/>Candle {zone.candleIndex} · {zone.low}–{zone.high}<br/>{zone.state} · {zone.touches} touch(es) · {zone.departureMultiple.toFixed(2)}x departure<ul>{zone.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></Diagnostic>)}{live.detection.rejected.length>0&&<Diagnostic><strong>Rejected candidates</strong><ul>{live.detection.rejected.slice(0,8).map(item=><li key={`${item.candleIndex}-${item.reason}`}>Candle {item.candleIndex}: {item.reason}</li>)}</ul></Diagnostic>}</Diagnostics>}
    {live&&source==='live'&&<Diagnostics>{live.runwayChecks.map(check=><Diagnostic key={check.zoneId}><strong>{check.allowed?'2:1 RUNWAY CLEAR':'TRADE BLOCKED'}</strong><br/>{check.reason}<br/>Entry {check.entry} · SL {check.stopLoss} · TP {check.takeProfit}</Diagnostic>)}</Diagnostics>}
    {live&&source==='live'&&<Ledger><table><thead><tr><th>Confirmation</th><th>Zone</th><th>Side</th><th>Prior touches</th><th>MTF</th><th>M15 trend</th><th>Score</th><th>Entry</th><th>SL</th><th>TP</th><th>Outcome</th></tr></thead><tbody>{[...live.historicalEntrySetups].sort((a,b)=>b.confirmationTime-a.confirmationTime).slice(0,250).map((setup,index)=><tr key={`${setup.zone.id}-${setup.confirmationTime}-${index}`}><td>{new Date(setup.confirmationTime*1000).toLocaleString()}</td><td>{setup.zone.kind}</td><td>{setup.zone.side}</td><td>{setup.zone.touches}</td><td>{setup.zone.timeframeConfluence?.timeframeCount??1}/3</td><td>{setup.trend.toUpperCase()}</td><td>{setup.score?.total??0} / {setup.score?.minimumScore??0}</td><td>{setup.runway.entry}</td><td>{setup.runway.stopLoss}</td><td>{setup.runway.takeProfit}</td><td className={setup.outcome}>{setup.outcome.toUpperCase()}</td></tr>)}</tbody></table></Ledger>}
    <Legend><Rule><strong>Demo pipeline</strong><br/>M15 trend → M5 zones → M1 touch candle and later M1 close-through confirmation.</Rule><Rule><strong>Continuation</strong><br/>No subjective choppiness filter. A zone exists when the explicit candle, leg-position, separation, and departure rules qualify it.</Rule><Rule><strong>MTF confluence</strong><br/>MTF 2/3 means the trade zone overlapped same-side zones across M1, M5, and M15 at that historical moment.</Rule><Rule><strong>Gate before score</strong><br/>Invalid zones, stale confirmation, blocked 2:1 runway, spread, session, or news failures are rejected before points are calculated.</Rule></Legend>
  </Page>;
}
